# Generated by Django 2.1.8 on 2019-11-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('name', models.CharField(max_length=40, verbose_name='课程名称')),
                ('kind', models.CharField(choices=[('compulsory', '必修课'), ('elective', '选修课')], default='必修课', max_length=10, verbose_name='课程类别')),
                ('pub_date', models.DateField(verbose_name='发布时间')),
                ('credit', models.FloatField(verbose_name='学分')),
            ],
            options={
                'verbose_name_plural': '课程',
                'ordering': ['pub_date', 'department'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course', verbose_name='课程')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('teacher', '教师'), ('student', '学生')], default='学生', max_length=10)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courseselect.User', verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courseselect.User', verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name_plural': '教师',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Department', verbose_name='所属院系'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Teacher', verbose_name='授课教师'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courseselect.Course', verbose_name='已选课程'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Department', verbose_name='所属院系'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='courseselect.Teacher', verbose_name='授课教师'),
        ),
    ]
