# Generated by Django 2.1.8 on 2019-11-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False, verbose_name='教室编号')),
                ('site', models.CharField(choices=[('1', '教1'), ('2', '教2')], default='教1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('name', models.CharField(max_length=40, verbose_name='课程名称')),
                ('kind', models.CharField(choices=[('compulsory', '必修课'), ('elective', '选修课')], default='必修课', max_length=10, verbose_name='课程类别')),
                ('pub_date', models.DateField(verbose_name='发布时间')),
                ('credit', models.FloatField(verbose_name='学分')),
                ('selected_now', models.IntegerField(verbose_name='已选课人数')),
                ('selected_limit', models.IntegerField(verbose_name='选课人数上限')),
                ('start_week', models.IntegerField(default=1, verbose_name='开始周次')),
                ('end_week', models.IntegerField(default=20, verbose_name='结束周次')),
                ('arr_course', models.IntegerField(default=0, verbose_name='第几节')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Classroom', verbose_name='上课教室')),
            ],
            options={
                'verbose_name_plural': '课程',
                'ordering': ['pub_date', 'department'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='院系名称')),
            ],
            options={
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('courses', models.ManyToManyField(to='courseselect.Course', verbose_name='已选课程')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default='0', verbose_name='成绩')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course', verbose_name='课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Teacher', verbose_name='授课教师')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='123', max_length=20)),
                ('kind', models.CharField(choices=[('teacher', '教师'), ('student', '学生')], default='学生', max_length=10, verbose_name='用户属性')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default='wangjian192@mails.ucas.edu.cn', max_length=254, verbose_name='电子邮件')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.User', verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='student',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.User', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Department', verbose_name='所属院系'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='courseselect.Teacher', verbose_name='授课教师'),
        ),
    ]
