# Generated by Django 2.1.8 on 2019-11-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['pub_date', 'department'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='courseselect.Teacher', verbose_name='授课教师'),
        ),
    ]
