# Generated by Django 2.1.8 on 2019-11-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': '教室'},
        ),
        migrations.AlterField(
            model_name='course',
            name='selected_now',
            field=models.IntegerField(default=0, verbose_name='已选课人数'),
        ),
    ]
