# Generated by Django 2.1.8 on 2019-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0002_auto_20191107_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['pub_date', 'department'], 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '院系'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '教师'},
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courseselect.Course', verbose_name='已选课程'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号'),
        ),
    ]
