# Generated by Django 2.1.8 on 2019-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0002_auto_20191115_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name_plural': '选课及成绩'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='kind',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='atrribute',
            field=models.BooleanField(default=False, verbose_name='学位课'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('teacher', '教师'), ('student', '学生')], default='teacher', max_length=10, verbose_name='用户属性'),
        ),
    ]
