# Generated by Django 2.1.8 on 2019-11-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0003_auto_20191107_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='课程id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, to='courseselect.Course', verbose_name='已选课程'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Student'),
        ),
    ]
