# Generated by Django 2.1.8 on 2019-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0003_auto_20191117_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='atrribute',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='attribute',
            field=models.CharField(choices=[('is', 'is'), ('not', 'not')], default='not', max_length=10, verbose_name='学位课'),
        ),
    ]
