# Generated by Django 2.1.8 on 2019-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0005_auto_20191119_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startdate',
            options={'verbose_name': '选课开始时间', 'verbose_name_plural': '选课开始时间'},
        ),
        migrations.AlterField(
            model_name='startdate',
            name='date',
            field=models.DateTimeField(verbose_name='选课开始时间'),
        ),
    ]
