# Generated by Django 2.1.8 on 2019-11-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0005_auto_20191111_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('g_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Student')),
            ],
        ),
    ]
