# Generated by Django 2.1.8 on 2019-11-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0006_auto_20191119_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startdate',
            old_name='date',
            new_name='check_time',
        ),
    ]
