# Generated by Django 2.1.8 on 2019-11-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0006_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courseselect.Course', verbose_name='已选课程'),
        ),
    ]
