# Generated by Django 2.1.8 on 2019-11-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0007_auto_20191119_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courseselect.User', verbose_name='学号'),
        ),
    ]
