# Generated by Django 2.1.8 on 2019-12-01 05:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0008_auto_20191121_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='选课开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='选课结束时间')),
            ],
            options={
                'verbose_name': '选课开始结束时间',
                'verbose_name_plural': '选课开始结束时间',
            },
        ),
        migrations.CreateModel(
            name='Pre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '预选课',
                'verbose_name_plural': '预选课',
            },
        ),
        migrations.DeleteModel(
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='arr_course',
        ),
        migrations.AddField(
            model_name='course',
            name='hot_value',
            field=models.IntegerField(default=0, verbose_name='热度值'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.IntegerField(default=0, verbose_name='开始节'),
        ),
        migrations.AddField(
            model_name='course',
            name='weekdays',
            field=models.IntegerField(default=0, verbose_name='周几'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_week',
            field=models.IntegerField(default=0, verbose_name='结束节'),
        ),
        migrations.AddField(
            model_name='pre',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Course'),
        ),
        migrations.AddField(
            model_name='pre',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.Student'),
        ),
    ]
