# Generated by Django 2.1.8 on 2019-12-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0011_auto_20191201_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='公告标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('excerpt', models.CharField(max_length=100, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_time'],
            },
        ),
    ]
